---
title: Curriculum Vitae
author: "Brandi Patrice Smith, PhD, MS"
email: "bsmith15@cdc.gov"
output:
  html_document:
    df_print: paged
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=1in
github: brandis2
jobtitle: Prevention Effectiveness Fellow
keywords: R Markdown, academic CV, template
linkcolor: black
fontawesome: yes
address: Atlanta, GA 30038
twitter: brandipsmith92
updated: yes
urlcolor: blue
web: brandi-smith.com
---

***
### Education  

#### Doctor of Philosophy in Health and Medical Informatics 
*University of Illinois at Urbana-Champaign (UIUC)*  
2021

#### Masters of Science in Mathematics 
*Mississippi State University*  
2016

#### Bachelors of Science in Mathematics 
*Mississippi Valley State University*  
2014  

### Research Experience

##### Steven M. Teutsch Prevention Effectivenss Fellow | Public Health & Analytics Modeling Track, Centers for Diesease Control and Prevention 2021 -   

* Assist with data science projects within the National Center of Injury Prevention and Control (NCIPC)


##### Research Assistant in Rebecca Lee Smith's Lab (UIUC), 2019 - 2021  

* Evaluated data from the Midlife Womens Health Study  
* Compared statistical learning models for phthalate exposure analysis 
* Determined racial differences in factors related to health and demographics and its effects on menopausal quality of life  

##### Research Assistant in Jodi Schneider's Lab (UIUC), 2020  

* Evaluation and optimization of systematic review tools using R, Python and SQL

##### Data Analyst at Dow Agrosciences - Research Park (UIUC), 2017  

* Analyzed gene expressions from toxicogenomics databases for drug development purposes using R and SQL

##### Research Assistant in	Zeynep Madak-Erdogan's Lab (UIUC), 2016 - 2019  

* RNA sequence analysis – trim, map, align, read, and statistical analysis to identify differentially expressed genes using Linux and R

### Teaching Experience  

##### Teaching Assistant – to Dr. Alexander Lipka, Applied Statistical Methods I  
*University of Illinois at Urbana Champaign, FA 2019*  

* Review, discuss, and test students on statistical concepts including – descriptive statistics, probability, and statistical inferences – use of R and SAS

##### Instructor – College and Intermediate Algebra  
*Mississippi Valley State University, SUM 2019*  

* Taught and reviewed algebraic concepts including – linear and quadratic equations, inequalities, and higher order polynomials
	
##### Teaching Assistant – to instructor Michael Haberman Introduction to Python for Data Science  
*University of Illinois at Urbana-Champaign, FA 2018*  

* Discussion of fundamental programming functions through Piazza web platform  
* Grading of programming projects  


### Publications  

#### First Author Manuscripts:

1. ##### [Racial Differences in Lifestyle, Demographic, and Health Factors Associated with Quality of Life (QoL) in Midlife Women](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7788772/)  
**Smith, Brandi Patrice**, Cardoso-Mendoza E, Flaws JA, Madak-Erdogan Z, Smith RL. Racial differences in lifestyle, demographic, and health factors associated with quality of life (QoL) in midlife women. Womens Midlife Health. 2021;7(1):2. Published 2021 Jan 6. doi:10.1186/s40695-020-00060-1  


2. ##### [Identification of early liver toxicity gene biomarkers using comparative supervised machine learning.](https://doi.org/10.1038/s41598-020-76129-8) 
**Smith, B.P.**, Auvil, L.S., Welge, M. et al. Identification of early liver toxicity gene biomarkers using comparative supervised machine learning. Sci Rep 10, 19128 (2020). https://doi.org/10.1038/s41598-020-76129-8

3. ##### [A machine learning based approach to identify biomarkers of environmental toxicant exposures relevant to liver cancer disparities in rural Illinois](https://cancerres.aacrjournals.org/content/79/13_Supplement/5124.short)  
**Brandi Smith**, Zeynep Madak-Erdogan. A machine learning based approach to identify biomarkers of environmental toxicant exposures relevant to liver cancer disparities in rural Illinois [abstract]. In: Proceedings of the American Association for Cancer Research Annual Meeting 2019; 2019 Mar 29-Apr 3; Atlanta, GA. Philadelphia (PA): AACR; Cancer Res 2019;79(13 Suppl):Abstract nr 5124.  

4. ##### [Urban Neighborhood and Residential Factors Associated with Breast Cancer in African American Women: A Systematic Review](https://doi.org/10.1007/s12672-018-0325-x)  
**Smith, Brandi Patrice**, and Zeynep Madak-Erdogan. “Urban Neighborhood and Residential Factors Associated with Breast Cancer in African American Women: A Systematic Review.” Hormones and Cancer 9, no. 2 (April 2018): 71–81.  

### Co-Authored Manuscripts:

1. ##### [Suppression of FOXM1 Activities and Breast Cancer Growth in Vitro and in Vivo by a New Class of Compounds](https://doi.org/10.1038/s41523-019-0141-7)  
Ziegler, Yvonne, Mary J. Laws, Valeria Sanabria Guillen, Sung Hoon Kim, Parama Dey, **Brandi P. Smith**, Ping Gong, et al. “Suppression of FOXM1 Activities and Breast Cancer Growth in Vitro and in Vivo by a New Class of Compounds.” Npj Breast Cancer 5, no. 1 (December 2019): 45.   

2. ##### [Combined Targeting of Estrogen Receptor Alpha and XPO1 Prevent Akt Activation, Remodel Metabolic Pathways and Induce Autophagy to Overcome Tamoxifen Resistance](https://doi.org/10.3390/cancers11040479)  
Kulkoyluoglu-Cotul, Eylem, **Brandi Patrice Smith**, Kinga Wrobel, Yiru Chen Zhao, Karen Lee Ann Chen, Kadriye Hieronymi, Ozan Berk Imir, et al. “Combined Targeting of Estrogen Receptor Alpha and XPO1 Prevent Akt Activation, Remodel Metabolic Pathways and Induce Autophagy to Overcome Tamoxifen Resistance.” Cancers 11, no. 4 (April 4, 2019): 479.  

3. ##### [Free Fatty Acids Rewire Cancer Metabolism in Obesity-Associated Breast Cancer via Estrogen Receptor and MTOR Signaling](https://doi.org/10.1158/0008-5472.CAN-18-2849)  
Madak-Erdogan, Zeynep, Shoham Band, Yiru Chen Zhao, **Brandi Patrice Smith**, Eylem Kulkoyluoglu-Cotul, Qianying Zuo, Ashlie Santaliz Casiano, et al. “Free Fatty Acids Rewire Cancer Metabolism in Obesity-Associated Breast Cancer via Estrogen Receptor and MTOR Signaling.” Cancer Research, March 12, 2019, canres.2849.2018. 

### Honors
**Top 30 Selected for Russell Sage Foundation Summer Institute in Social-Science Genomics** - 2019  

**Early Career Forum Travel Award**, The Endocrine Society - 2019  

**AACR Minority Scholar in Cancer Research Award**, American Association of Cancer Research (AACR) - 2018  

**Interdisciplinary Environmental Toxicology Scholarship**, University of Illinois at Urbana-Champaign (UIUC) - 2018  

**Selected for Purdue Intensive Summer Boot Camp for “Big Data Training for Translational Omics Research”**, Purdue University - 2018  

**AACR-Bristol Myers Squibb Oncology Scholar-in-Training Award**, American Association of Cancer Research - 2018  

**Future Leaders Advancing Research in Endocrinology (FLARE) Fellowship**, Endocrine Society - 2018  


**Early Career Cancer Health Disparities Scholarships**, Cancer Disparities Research Network - 2017  

**Carl Storm Underrepresented Minority (CSURM) Fellowship**, Gordon Research Conferences - 2017  

**Endocrine Society Summer Research Fellowship**, Endocrine Society - 2017  



### Memberships
**American Medical Informatics Association (AMIA)**, Member - 2018  

**Future Leaders Advancing Research in Endocrinology (FLARE)**, Alumni - 2018  

**Cancer Disparities Research Network	(CDRN)** -2017  

**American Association of Cancer Research (AACR)**, Member - 2017  

**Delta Sigma Theta Sorority, Inc., Education Committee, Technology Committee** - 2017  

**Endocrine Society, Committee of Diversity and Inclusion Intern** - 2017  

**Champaign County Medical Reserves Corps** - 2016  


### Skills
* Bioinformatics  
    + RNA-sequence analysis  
    + Microarray analysis  
    
* R Statistical Language  
* Python
* SQL

***
